#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libxkbfile
Version  : 1.0.9
Release  : 10
URL      : http://xorg.freedesktop.org/releases/individual/lib/libxkbfile-1.0.9.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/lib/libxkbfile-1.0.9.tar.gz
Summary  : The xkbfile Library
Group    : Development/Tools
License  : HPND
Requires: libxkbfile-lib
BuildRequires : pkgconfig(kbproto)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xorg-macros)

%description
All questions regarding this software should be directed at the
Xorg mailing list:

%package dev
Summary: dev components for the libxkbfile package.
Group: Development
Requires: libxkbfile-lib

%description dev
dev components for the libxkbfile package.


%package lib
Summary: lib components for the libxkbfile package.
Group: Libraries

%description lib
lib components for the libxkbfile package.


%prep
%setup -q -n libxkbfile-1.0.9

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/XKBbells.h
/usr/include/X11/extensions/XKBconfig.h
/usr/include/X11/extensions/XKBfile.h
/usr/include/X11/extensions/XKBrules.h
/usr/include/X11/extensions/XKM.h
/usr/include/X11/extensions/XKMformat.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
