#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : libxkbfile
Version  : 1.1.0
Release  : 11
URL      : http://xorg.freedesktop.org/releases/individual/lib/libxkbfile-1.1.0.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/lib/libxkbfile-1.1.0.tar.gz
Source99 : http://xorg.freedesktop.org/releases/individual/lib/libxkbfile-1.1.0.tar.gz.sig
Summary  : X11 keyboard file manipulation library
Group    : Development/Tools
License  : HPND
Requires: libxkbfile-lib = %{version}-%{release}
Requires: libxkbfile-license = %{version}-%{release}
BuildRequires : pkgconfig(kbproto)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xorg-macros)

%description
libxkbfile - XKB file handling routines
---------------------------------------
libxkbfile is used by the X servers and utilities to parse the XKB
configuration data files.

%package dev
Summary: dev components for the libxkbfile package.
Group: Development
Requires: libxkbfile-lib = %{version}-%{release}
Provides: libxkbfile-devel = %{version}-%{release}
Requires: libxkbfile = %{version}-%{release}

%description dev
dev components for the libxkbfile package.


%package lib
Summary: lib components for the libxkbfile package.
Group: Libraries
Requires: libxkbfile-license = %{version}-%{release}

%description lib
lib components for the libxkbfile package.


%package license
Summary: license components for the libxkbfile package.
Group: Default

%description license
license components for the libxkbfile package.


%prep
%setup -q -n libxkbfile-1.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552834564
export LDFLAGS="${LDFLAGS} -fno-lto"
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1552834564
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libxkbfile
cp COPYING %{buildroot}/usr/share/package-licenses/libxkbfile/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/XKBbells.h
/usr/include/X11/extensions/XKBconfig.h
/usr/include/X11/extensions/XKBfile.h
/usr/include/X11/extensions/XKBrules.h
/usr/include/X11/extensions/XKM.h
/usr/include/X11/extensions/XKMformat.h
/usr/lib64/libxkbfile.so
/usr/lib64/pkgconfig/xkbfile.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libxkbfile.so.1
/usr/lib64/libxkbfile.so.1.0.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libxkbfile/COPYING
