#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : libxkbfile
Version  : 1.1.0
Release  : 14
URL      : http://xorg.freedesktop.org/releases/individual/lib/libxkbfile-1.1.0.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/lib/libxkbfile-1.1.0.tar.gz
Source1  : http://xorg.freedesktop.org/releases/individual/lib/libxkbfile-1.1.0.tar.gz.sig
Summary  : The xkbfile Library
Group    : Development/Tools
License  : HPND
Requires: libxkbfile-lib = %{version}-%{release}
Requires: libxkbfile-license = %{version}-%{release}
BuildRequires : pkgconfig(kbproto)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xorg-macros)

%description
libxkbfile - XKB file handling routines
---------------------------------------
libxkbfile is used by the X servers and utilities to parse the XKB
configuration data files.

%package dev
Summary: dev components for the libxkbfile package.
Group: Development
Requires: libxkbfile-lib = %{version}-%{release}
Provides: libxkbfile-devel = %{version}-%{release}
Requires: libxkbfile = %{version}-%{release}

%description dev
dev components for the libxkbfile package.


%package lib
Summary: lib components for the libxkbfile package.
Group: Libraries
Requires: libxkbfile-license = %{version}-%{release}

%description lib
lib components for the libxkbfile package.


%package license
Summary: license components for the libxkbfile package.
Group: Default

%description license
license components for the libxkbfile package.


%prep
%setup -q -n libxkbfile-1.1.0
cd %{_builddir}/libxkbfile-1.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604609922
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1604609922
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libxkbfile
cp %{_builddir}/libxkbfile-1.1.0/COPYING %{buildroot}/usr/share/package-licenses/libxkbfile/4f35a76dbcc982e002982b97c5d93f3d95c5e57f
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/XKBbells.h
/usr/include/X11/extensions/XKBconfig.h
/usr/include/X11/extensions/XKBfile.h
/usr/include/X11/extensions/XKBrules.h
/usr/include/X11/extensions/XKM.h
/usr/include/X11/extensions/XKMformat.h
/usr/lib64/libxkbfile.so
/usr/lib64/pkgconfig/xkbfile.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libxkbfile.so.1
/usr/lib64/libxkbfile.so.1.0.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libxkbfile/4f35a76dbcc982e002982b97c5d93f3d95c5e57f
